### ISSUE TITLE
Unable to urlify properly

### ISSUE THREAD

**Issue by fracasula** [jbroadway/urlify#35]
Hi there,

I've been trying to urlify a very simple string but the last part is being dropped. It's probably a wanted behaviour but it could be useful if there may be an option to avoid that.

My string is "Brazilian Série A" and I want it to become "brazilian-serie-a". It becomes "brazilian-serie" instead without the final "-a" part. Any way I can do this?

Below my code:

    \URLify::filter('Brazilian Série A') // produces "brazilian-serie"

Tried also with:

    \URLify::filter('Brazilian Série A', 120, 'en') // produces "brazilian-serie"

**Comment by fracasula** [comment]
OK, I figured out what's going on here. The "A" is being removed because part of the English common words. Changing the `$remove_list` public attribute solves the issue :+1:

**Comment by jbroadway** [comment]
Was just about to hop on and mention the remove list. Glad you got it working :)
