### ISSUE TITLE
Passing certain characters to add_chars() method causes "preg_match_all(): Unknown modifier ']'"

### ISSUE THREAD

**Issue by cbj4074** [jbroadway/urlify#55]
Consider the following:

```php
URLify::add_chars(['/' => '']);
```

This causes a language exception, `preg_match_all(): Unknown modifier ']'`, because the `/` character is used as the regular expression delimiter within the URLify library.

The above example derives from a fairly common and reasonable use-case: I want to remove all illegal characters from a file name, and on UNIX and Windows, `/` is illegal.

To fix this, PHP's `preg_quote()` function must be called on the keys in the array argument passed to `add_chars()`.

I'll submit a PR shortly that seeks to fix the issue.

**Comment by lux** [comment]
Fixed in https://github.com/jbroadway/urlify/pull/56
